apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consentinel.fullname" . }}-config
  labels:
    {{- include "consentinel.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  REDIS_URL: "redis://{{ include "consentinel.fullname" . }}-redis-master:6379/0"
